### ISSUE TITLE
Slack bot integration Error: not_allowed_token_type

### ISSUE THREAD

**Issue by ImagineerNL** [shayaantx/botdarr#123]
Trying to install this as a slack bot.

Created the app, added the oauth permissions as per instruction.
Copy/pasted the SLACK_BOT_TOKEN from the slack app settings "Bot User OAuth Token" , but get this error in my logs and it won't connect to slack.

> exception in thread "main" java.lang.IllegalStateException: Failed to the RTM endpoint URL (error: not_allowed_token_type)
>         at com.github.seratch.jslack.Slack.rtmConnect(Slack.java:157)
>         at com.github.seratch.jslack.Slack.rtmConnect(Slack.java:132)
>         at com.github.seratch.jslack.Slack.rtm(Slack.java:123)
>         at com.botdarr.clients.slack.SlackBootstrap.init(SlackBootstrap.java:36)
>         at com.botdarr.BotdarrApplication.main(BotdarrApplication.java:13)

I'm using the docker app from the Unraid appdir, and manually added the needed variables from the readme.

Total log seems error free besides a lidarr warning (i dont have lidarr):

> May 27, 2024 9:28:20 PM org.flywaydb.core.internal.logging.slf4j.Slf4jLog info
> INFO: Flyway Community Edition 6.2.4 by Redgate
> May 27, 2024 9:28:20 PM org.flywaydb.core.internal.logging.slf4j.Slf4jLog info
> INFO: Database: jdbc:sqlite:database/botdarr.db (SQLite 3.30)
> May 27, 2024 9:28:20 PM org.flywaydb.core.internal.logging.slf4j.Slf4jLog info
> INFO: Successfully validated 3 migrations (execution time 00:00.010s)
> May 27, 2024 9:28:20 PM org.flywaydb.core.internal.logging.slf4j.Slf4jLog info
> INFO: Current version of schema "main": 3
> May 27, 2024 9:28:20 PM org.flywaydb.core.internal.logging.slf4j.Slf4jLog info
> INFO: Schema "main" is up to date. No migration necessary.
> Exception in thread "main" java.lang.IllegalStateException: Failed to the RTM endpoint URL (error: not_allowed_token_type)
>         at com.github.seratch.jslack.Slack.rtmConnect(Slack.java:157)
>         at com.github.seratch.jslack.Slack.rtmConnect(Slack.java:132)
>         at com.github.seratch.jslack.Slack.rtm(Slack.java:123)
>         at com.botdarr.clients.slack.SlackBootstrap.init(SlackBootstrap.java:36)
>         at com.botdarr.BotdarrApplication.main(BotdarrApplication.java:13)
> 2024-May-27 21:28:20 PM [main] WARN  com.botdarr.Config - Lidarr commands are not enabled, make sure you set the lidarr url, path, token, default profile
> 
> ** Press ANY KEY to close this window **

**Comment by shayaantx** [comment]
@ImagineerNL ill run thru steps 2moro night or next night and see if i can reproduce

**Comment by shayaantx** [comment]
@ImagineerNL I ran through https://github.com/shayaantx/botdarr/wiki/Install-Slack-Bot and didn't have an issue (well I was running an older jdk 8 and got certificate errors, but once I upgraded it was fine)

I did update slack api https://github.com/shayaantx/botdarr/pull/124, but I couldn't reproduce your error

Did you create a classic app? or a modern one? (looks like eventually classic apps are gonna die, so guess these instructions will need to change)

![image](https://github.com/shayaantx/botdarr/assets/5449086/aca4ab0e-d4c0-4655-9909-798581a588cc)

If you're on discord or matrix or slack, post your handle, and I can look at your issue live too

**Comment by ImagineerNL** [comment]
I'll dig a bit further in what it might be, thanks for looking.
I assume it was a classic app, that might have been the issue

**Comment by ACupOfAvgJoe** [comment]
classic Slack apps are no longer supported, any chance there will be support for modern apps? getting the same not_allowed_token_type error.

**Comment by ImagineerNL** [comment]
> I did update slack api #124, but I couldn't reproduce your error

Would it be possible to push this to live (and to the docker version)?
 
> Did you create a classic app? or a modern one? (looks like eventually classic apps are gonna die, so guess these instructions will need to change)

Modern App, as Classic apps cannot be created anymore.

**Comment by shayaantx** [comment]
@ImagineerNL @ACupOfAvgJoe I will spend some time this week going through that PR and see what I can do to get it working again

**Comment by shayaantx** [comment]
@ImagineerNL @ACupOfAvgJoe 

I spent some time tonight updating the PR to get off RTM mode and onto socket mode for slack modern apps, see https://github.com/shayaantx/botdarr/pull/124/commits/6392b192944da2b1cb2deb1ec52e8c99a2dd8921

I've also made a new wiki page for creating modern slack apps to work with the bot in general here https://github.com/shayaantx/botdarr/wiki/(wip)-Install-Slack-Bot-via-Slack-modern-app

Both are still wip

I will work on it more tomorrow night.

**Comment by ImagineerNL** [comment]
Thank you.
With this updated wiki it is at least connecting to the slack channel without errors.
The integration itself is not working yet, but that would probably be the PR you're still working on.

The only error still in the log is from lidarr, which i dont use and i have removed the docker variables 
`2025-Jan-09 14:44:56 PM [main] WARN  com.botdarr.Config - Lidarr commands are not enabled, make sure you set the lidarr url, path, token, default profile`

**Comment by shayaantx** [comment]
> Thank you. With this updated wiki it is at least connecting to the slack channel without errors. The integration itself is not working yet, but that would probably be the PR you're still working on.
> 
> The only error still in the log is from lidarr, which i dont use and i have removed the docker variables `2025-Jan-09 14:44:56 PM [main] WARN com.botdarr.Config - Lidarr commands are not enabled, make sure you set the lidarr url, path, token, default profile`

That warning occurs when you don't have lidarr configured (you can ignore it if you don't use lidarr)

Yea it def won't work without changes, hopefully I can get bulk of it working tonight

**Comment by ImagineerNL** [comment]
i didnt assume that one had anything to do with this item; just noted it as an fyi, as that is the only one that comes up as 'unconfigured', while all other integrations that arent configured dont show up in the log either.

And no rush; take your time.

**Comment by shayaantx** [comment]
@ImagineerNL I pushed the fixes for latest version 5.6.16, the wiki is updated with all required scopes

I tested most functionality of the bot via slack and it all seems to work, lemme know if you find any issues, otherwise I'll close the issue

**Comment by ImagineerNL** [comment]
Updated the docker, Followed the updated wiki, no new errors.

And at least now i get a message in log, so i know the slack socket connection is open
`Jan 12, 2025 11:27:02 PM com.slack.api.socket_mode.impl.SocketModeClientTyrusImpl onOpen INFO: New session is open (session id:XXXXXXXXX`

And a timeout message popped up in slack 'Error - Request failed with status code=404, reason=Not Found' which was resolved by setting SONARR_V4 to true.
So i know the connection is working.
It's just not responding to '$help' etc (i've tried the command prefix at '!' and '$' , so far no response)

I'm guessing it's an error with the scopes, and for now i'll need to dig in to it a bit more to see what i'm missing. 
I might eventually be better off to scrap the current fiddled 'slack-app' and start a new one from scratch following the wiki. 
 
 It seems no action on your part is needed yet.
 Thanks for your hard work so far!

**Comment by shayaantx** [comment]
> Updated the docker, Followed the updated wiki, no new errors.
> 
> And at least now i get a message in log, so i know the slack socket connection is open `Jan 12, 2025 11:27:02 PM com.slack.api.socket_mode.impl.SocketModeClientTyrusImpl onOpen INFO: New session is open (session id:XXXXXXXXX`
> 
> And a timeout message popped up in slack 'Error - Request failed with status code=404, reason=Not Found' which was resolved by setting SONARR_V4 to true. So i know the connection is working. It's just not responding to '$help' etc (i've tried the command prefix at '!' and '$' , so far no response)
> 
> I'm guessing it's an error with the scopes, and for now i'll need to dig in to it a bit more to see what i'm missing. I might eventually be better off to scrap the current fiddled 'slack-app' and start a new one from scratch following the wiki.
> 
> It seems no action on your part is needed yet. Thanks for your hard work so far!

lemme know if you want to debug it live on slack or discord

I noticed if you add scopes to the modern app, I had to reinstall the app to the workspace each time (as I was testing)

**Comment by shayaantx** [comment]
@ImagineerNL any issues ?

**Comment by shayaantx** [comment]
haven't heard back closing
