### ISSUE TITLE
Unexpected error via docker installation

### ISSUE THREAD

**Issue by shohart** [shayaantx/botdarr#27]
Hello! I am trying to make the whole thing work in docker environment.
After i configure the whole properties file i get following error

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.NullPointerException
	at com.botdarr.api.CacheProfileStrategy.cacheData(CacheProfileStrategy.java:14)
	at com.botdarr.api.radarr.RadarrApi.cacheData(RadarrApi.java:129)
	at com.botdarr.scheduling.Scheduler.initApiCaching(Scheduler.java:41)
	at com.botdarr.clients.ChatClientType.initScheduling(ChatClientType.java:325)
	at com.botdarr.clients.ChatClientType$2.init(ChatClientType.java:97)
	at com.botdarr.BotdarrApplication.main(BotdarrApplication.java:8)
```
here is my properties file
```
telegram-token=*sometoken*
telegram-private-channels=botdarr:***
radarr-url='http://loclhost:7878'
radarr-token=*sometoken*
radarr-default-profile="Russian 1080p"
radarr-path="/mnt/theVault/DOWNLOADS/Video/Movies"
sonarr-url='http://localhost:8989'
sonarr-token=*sometoken*
sonarr-default-profile="HD - 720p/1080p"
sonarr-path="/mnt/theVault/DOWNLOADS/Video/Serial"
lidarr-url='http://localhost:8686'
lidarr-token=*sometoken*
lidarr-path="/mnt/theVault/DOWNLOADS/LOseless/Tagged/"
lidarr-default-quality-profile="Lossless"
lidarr-default-metadata-profile="Standard"
command-prefix=!

```

I can feel that it may be wrong syntax but i found no example syntax in repo :((

upd: this [https://github.com/prometheus/cloudwatch_exporter/pull/317](url) looks relevant

**Comment by shayaantx** [comment]
Hi,

The syntax for your properties file looks fine so far (fyi you can use environment variables now instead of a raw properties files in docker setups)

So that stack trace is error-ing on missing profiles for radarr.

1. Are you sure "Russian 1080p" is a profile in your radarr setup?
2. Do you see any other errors in radarr, bot, network logs?

I will verify later today that spaces don't break the profile lookup logic (and I will fix NPE)

Let me know

Thanks

**Comment by shayaantx** [comment]
So I looked into it a little just now, the quotes around your urls are causing the issue (since I'm not stripping them). If you check the network log you should see something like Caused by: java.net.URISyntaxException: Illegal character in scheme name at index 0: 'http://192.168.1.196' etc etc.

I'd remove all single quotes and double quotes they shouldn't be necessary. Also confirmed spaces in profile names should be fine.

I haven't tested telegram client in awhile, so let me know if you have any other issues (I'll put up a PR later to fix the NPE and readme from other issue).

Also might strip out illegal characters from certain properties as well.

**Comment by shayaantx** [comment]
are you using the docker env variables and its automatically adding the quotes? cause if thats the case, let me know, and I'll put something more robust in (also I'll update my examples a bit more)

**Comment by shohart** [comment]
> I'd remove all single quotes and double quotes they shouldn't be necessary. Also confirmed spaces in profile names should be fine.

So i basically stripped all the quotes, and replaced 'localhost' with actual LAN address - 192.168.1.1. And everything started to work like a charm!

I tried without quotes but with 'localhost' addresses - and system gave me same error.
Maybe some docker-related issue... Strange I used 'localhost' for my various container.


> are you using the docker env variables and its automatically adding the quotes?

No, env variables are doing their job as they should... I think 'localhost' was an issue...

**Comment by shohart** [comment]
But every add command ends up with error 
Error! - Requested failed with exception, e=null

**Comment by shayaantx** [comment]
whats in network/radarr log?, sounds like bot can't connect to radarr (or other endpoints)

**Comment by shohart** [comment]
network.log:

```
2021-Feb-16 20:58:26 PM [pool-3-thread-1] ERROR com.botdarr.connections.ConnectionHelper - Error trying to process response
java.lang.NullPointerException: null
        at java.lang.String.startsWith(String.java:1405) ~[?:1.8.0_282]
        at java.lang.String.startsWith(String.java:1434) ~[?:1.8.0_282]
        at com.botdarr.api.sonarr.SonarrApi.isPathBlacklisted(SonarrApi.java:285) ~[botdarr-release.jar:?]
        at com.botdarr.api.sonarr.SonarrApi.access$300(SonarrApi.java:23) ~[botdarr-release.jar:?]
        at com.botdarr.api.sonarr.SonarrApi$6.getResponse(SonarrApi.java:201) ~[botdarr-release.jar:?]
        at com.botdarr.api.DownloadsStrategy.parseContent(DownloadsStrategy.java:54) ~[botdarr-release.jar:?]
        at com.botdarr.api.DownloadsStrategy$1.onSuccess(DownloadsStrategy.java:43) ~[botdarr-release.jar:?]
        at com.botdarr.api.DownloadsStrategy$1.onSuccess(DownloadsStrategy.java:40) ~[botdarr-release.jar:?]
        at com.botdarr.connections.ConnectionHelper.makeRequest(ConnectionHelper.java:57) ~[botdarr-release.jar:?]
        at com.botdarr.connections.ConnectionHelper.makeGetRequest(ConnectionHelper.java:28) ~[botdarr-release.jar:?]
        at com.botdarr.connections.ConnectionHelper.makeGetRequest(ConnectionHelper.java:24) ~[botdarr-release.jar:?]
        at com.botdarr.api.DownloadsStrategy.getContentDownloads(DownloadsStrategy.java:40) ~[botdarr-release.jar:?]
        at com.botdarr.api.PeriodicNotificationStrategy.sendPeriodicNotifications(PeriodicNotificationStrategy.java:22) ~[botdarr-release.jar:?]
        at com.botdarr.api.sonarr.SonarrApi.sendPeriodicNotifications(SonarrApi.java:96) ~[botdarr-release.jar:?]
        at com.botdarr.scheduling.Scheduler.lambda$initApiNotifications$0(Scheduler.java:29) ~[botdarr-release.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_282]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_282]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_282]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_282]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_282]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_282]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
2021-Feb-16 21:03:27 PM [pool-3-thread-1] ERROR com.botdarr.connections.ConnectionHelper - Error trying to process response
java.lang.NullPointerException: null
2021-Feb-16 21:08:27 PM [pool-3-thread-1] ERROR com.botdarr.connections.ConnectionHelper - Error trying to process response
java.lang.NullPointerException: null
2021-Feb-16 21:13:28 PM [pool-3-thread-1] ERROR com.botdarr.connections.ConnectionHelper - Error trying to process response
java.lang.NullPointerException: null
2021-Feb-16 21:18:28 PM [pool-3-thread-1] ERROR com.botdarr.connections.ConnectionHelper - Error trying to process response
java.lang.NullPointerException: null
2021-Feb-16 21:23:28 PM [pool-3-thread-1] ERROR com.botdarr.connections.ConnectionHelper - Error trying to process response
java.lang.NullPointerException: null
2021-Feb-16 21:28:29 PM [pool-3-thread-1] ERROR com.botdarr.connections.ConnectionHelper - Error trying to process response
java.lang.NullPointerException: null

```

radarr logs seem to be ok. btw i can search movies, can make !movie discover, but can not add one

**Comment by shayaantx** [comment]
What about the rest of the logs, that NPE you posted looks new (from blacklisted paths I added last PR). I can fix it that now, but that's not even called during add

There must be another NPE somewhere if you're getting Requested failed with exception, e=null

Also did you crop out rest of those NPE's? Are they the same as above one? (assume they are since they are every 5 minutes, i.e., when we send notifications)

**Comment by shayaantx** [comment]
I pushed 5.1.5 to docker (and to latest) with some NPE fixes and some additional logging.

Lemme know if you get more details on the error, if you still have trouble, my email is shayaantx@gmail.com.

I'm happy to look over teamviewer or whatever.

**Comment by shohart** [comment]
Updated version works fine as it seems. I have a couple of question about functionality, emailed you :)
