### ISSUE TITLE
Weird java error

### ISSUE THREAD

**Issue by sullystuff** [shayaantx/botdarr#38]
Hi, I am currently trying to run this program but I keep getting errors.  I have openjdk8 installed, and have made sure I've `chown`ed the directory. How do I fix this issue?
`carter@valor:/opt/requestrr3$ java -jar botdarr-release.jar
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
Exception in thread "main" java.lang.ExceptionInInitializerError
        at com.botdarr.BotdarrApplication.main(BotdarrApplication.java:7)
Caused by: java.lang.UnsupportedOperationException: No class provided, and an appropriate one cannot be found.
        at org.apache.logging.log4j.LogManager.callerClass(LogManager.java:576)
        at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:601)
        at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:588)
        at com.botdarr.database.Bootstrap.<clinit>(Bootstrap.java:53)
        ... 1 more
carter@valor:/opt/requestrr3$
`

**Comment by sullystuff** [comment]
NEVER MIND. Apparently it won't auto-detect which java version is needed, my bad.

**Comment by shayaantx** [comment]
np, fyi I am using/testing against whatever last opendjk 8 is from dockerhub. If you need support for a later version of java, let me know and I can take a look.

If you have any other issues, don't hesitate to let me know
