### ISSUE TITLE
Strange error via docker installation

### ISSUE THREAD

**Issue by mac-110** [shayaantx/botdarr#62]
i am currently trying to get botdarr running in a docker container under Unraid.

Property file looks following:

> telegram-token=*********:*********************
telegram-private-channels=****:-100************
radarr-url=http://192.168.1.100:7878
radarr-token=<omitted>
radarr-default-profile=Ultra-HD
radarr-path=/media/movies
max-downloads-to-show=20
max-results-to-show=20
command-prefix=!
timeout=5000
>

and I am getting following stack trace:

`Mar 13, 2022 9:19:40 PM org.flywaydb.core.internal.logging.slf4j.Slf4jLog info
INFO: Flyway Community Edition 6.2.4 by Redgate
Mar 13, 2022 9:19:40 PM org.flywaydb.core.internal.logging.slf4j.Slf4jLog info
INFO: Database: jdbc:sqlite:database/botdarr.db (SQLite 3.30)
Mar 13, 2022 9:19:40 PM org.flywaydb.core.internal.logging.slf4j.Slf4jLog info
INFO: Successfully validated 2 migrations (execution time 00:00.005s)
Mar 13, 2022 9:19:40 PM org.flywaydb.core.internal.logging.slf4j.Slf4jLog info
INFO: Current version of schema "main": 2
Mar 13, 2022 9:19:40 PM org.flywaydb.core.internal.logging.slf4j.Slf4jLog info
INFO: Schema "main" is up to date. No migration necessary.
2022-Mar-13 21:19:40 PM [main] WARN  com.botdarr.Config - Sonarr commands are not enabled, make sure you set the sonarr url, path, token, default profile
2022-Mar-13 21:19:40 PM [main] WARN  com.botdarr.Config - Lidarr commands are not enabled, make sure you set the lidarr url, path, token, default profile
2022-Mar-13 21:19:41 PM [pool-3-thread-1] ERROR com.botdarr.scheduling.Scheduler - Error during api notification
java.lang.NullPointerException: null
        at com.botdarr.clients.telegram.TelegramChatClient.lambda$sendMessage$1(TelegramChatClient.java:41) ~[botdarr-release.jar:?]
        at com.botdarr.clients.telegram.TelegramChatClient.sendMessages(TelegramChatClient.java:84) ~[botdarr-release.jar:?]
        at com.botdarr.clients.telegram.TelegramChatClient.sendMessage(TelegramChatClient.java:39) ~[botdarr-release.jar:?]
        at com.botdarr.clients.telegram.TelegramChatClient.sendToConfiguredChannels(TelegramChatClient.java:91) ~[botdarr-release.jar:?]
        at com.botdarr.scheduling.Scheduler.lambda$initApiNotifications$0(Scheduler.java:36) ~[botdarr-release.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_322]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_322]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_322]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_322]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_322]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_322]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_322]`

Seems to be something with the telegram api

**Comment by mac-110** [comment]
I found the problem, it was the -100 in front of the channel id

**Comment by shayaantx** [comment]
I'll fix the null pointer

**Comment by shayaantx** [comment]
are you using latest version?

**Comment by shayaantx** [comment]
latest version should have fix, also you should change your radarr token (if you make your radarr instance public to the internet) as you included it in your original post (I removed it)

**Comment by shayaantx** [comment]
also please let me know if you have any further issues

**Comment by mac-110** [comment]
Thx, but I do not plan to make my radarr public!
Everything is working fine now, thank you very much!

Best Ragrds,

Alex

**Comment by mac-110** [comment]
it is working like a charm now! is it anyhow possible to add interactive add buttons to the shows/movies offers which you get in telegram so that  there will be no need to copy paste add id ... ?!

**Comment by shayaantx** [comment]
its possible, just been busy lately with work, I added this ticket for it https://github.com/shayaantx/botdarr/issues/64

I might have some time this weekend to get some outstanding enhancements
