### ISSUE TITLE
lidarr telegram issues

### ISSUE THREAD

**Issue by axelmvt** [shayaantx/botdarr#85]
Hello!
I'm running botdarr with docker-compose. Newly deploy, and I'm getting the following issue every time I type a command:

`[OkHttp https://api.telegram.org/...] ERROR com.botdarr.clients.ChatClientBootstrap - Error during telegram updates
java.lang.NullPointerException: null
	at com.botdarr.clients.telegram.TelegramBootstrap.lambda$init$2(TelegramBootstrap.java:41) ~[botdarr-release.jar:?]
	at com.pengrad.telegrambot.impl.UpdatesHandler$1.onResponse(UpdatesHandler.java:73) [botdarr-release.jar:?]
	at com.pengrad.telegrambot.impl.UpdatesHandler$1.onResponse(UpdatesHandler.java:49) [botdarr-release.jar:?]
	at com.pengrad.telegrambot.impl.TelegramBotClient$1.onResponse(TelegramBotClient.java:52) [botdarr-release.jar:?]
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:216) [botdarr-release.jar:?]
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) [botdarr-release.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_332]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_332]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_332]`

this is how the compose file is:

> botdarr:
>     image: shayaantx/botdarr:latest
>     container_name: botdarr
>     environment:
>        TELEGRAM_TOKEN: ******
>        TELEGRAM_PRIVATE_CHANNELS: Test_channel:8********
>        LIDARR_URL: http://192.168.10.242:8686
>        LIDARR_TOKEN: ******
>        LIDARR_DEFAULT_QUALITY_PROFILE: Standard
>        LIDARR_DEFAULT_METADATA_PROFILE: Standard
>        LIDARR_PATH: /home/****/1tb/music
>        LIDARR_URL_BASE: 
>        COMMAND_PREFIX: !
>        MAX_DOWNLOADS_TO_SHOW: 20
>        MAX_RESULTS_TO_SHOW: 20
>     volumes:
>        - /home/****/docker/lidarr/logs:/home/botdarr/logs
>        - /home/****/docker/lidarr/database:/home/botdarr/database

Any idea what the issue might be? 

Thanks :D

**Comment by shayaantx** [comment]
assuming you're running the latest version, it would see like something is wrong with the callback data
![image](https://user-images.githubusercontent.com/5449086/206030820-442b4b66-438a-4018-9809-c596609cb947.png)

I'll setup up telegram setup later tonight and see if I can reproduce.

If I can't whats your telegram, we can troubleshoot together over telegram

@axelmvt

**Comment by axelmvt** [comment]
Oh great! Thanks! its @acelmvt. Appreciated!

**Comment by axelmvt** [comment]
I was able to fix the issue by commenting TELEGRAM_PRIVATE_CHANNELS and using TELEGRAM_PRIVATE_GROUPS. Only one of those is required!
