### ISSUE TITLE
Discord - 'This interaction failed' when adding 

### ISSUE THREAD

**Issue by BackedUpBooty** [shayaantx/botdarr#99]
Installed this with Docker on Synology for requesting new content on Lidarr only via Discord. 

App/bot is integrated in Discord, `!music...` etc. commands populate and give results in Discord. 

Two issues I have:

1. `!music-artist-add [name]` will show results in Discord but will not add the artist to lidarr
2. `!music-artist-find-new [name]` will show results with an `Add` button below each result. Clicking this button will add the artist to lidarr but Discord then shows a red error message `This interaction failed`. Except it didn't fail and the artist gets added and music gets grabbed (which is good, but I'm unsure why the error message). 

This error pops up in the logs from time to time:
```
[pool-3-thread-1] ERROR com.botdarr.scheduling.Scheduler - Error during api notification
net.dv8tion.jda.api.exceptions.InsufficientPermissionException: Cannot perform action due to a lack of Permission. Missing permission: MESSAGE_EMBED_LINKS
	at net.dv8tion.jda.internal.entities.AbstractChannelImpl.checkPermission(AbstractChannelImpl.java:329) ~[botdarr-release.jar:?]
	at net.dv8tion.jda.internal.entities.AbstractChannelImpl.checkPermission(AbstractChannelImpl.java:320) ~[botdarr-release.jar:?]
	at net.dv8tion.jda.internal.entities.TextChannelImpl.sendMessage(TextChannelImpl.java:359) ~[botdarr-release.jar:?]
	at com.botdarr.clients.discord.DiscordChatClient.lambda$sendToConfiguredChannels$0(DiscordChatClient.java:23) ~[botdarr-release.jar:?]
	at com.botdarr.clients.discord.DiscordChatClient.sendMessages(DiscordChatClient.java:43) ~[botdarr-release.jar:?]
	at com.botdarr.clients.discord.DiscordChatClient.sendToConfiguredChannels(DiscordChatClient.java:21) ~[botdarr-release.jar:?]
	at com.botdarr.scheduling.Scheduler.lambda$initApiNotifications$0(Scheduler.java:38) ~[botdarr-release.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_342]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_342]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_342]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_342]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_342]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_342]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_342]
```

I'm not sure where that missing permission is coming from. It showed up before so I kicked the bot, deleted it, recreated it and double checked that the 'Embed Links` box was checked in the OAuth URL generator (which it is). Same error persists.

**Comment by shayaantx** [comment]
@BackedUpBooty I'll take a look tonight or tomorrow night and get back to you

**Comment by shayaantx** [comment]
@BackedUpBooty so I can reproduce the issues you mentioned

I fixed the interaction failed + fixed it so !music-artist-add [name] and any add command that takes a string will actually display the add button (in discords case) as this would also happen for shows or movies

fyi that command when given a search string where there isn't an exact item for the string, will return results instead

You can pull the latest or 5.6.6 (should be pushed out shortly)

As for the random stack trace you were getting, does your bot have same permissions as documented in screenshots here https://github.com/shayaantx/botdarr/wiki/Install-Discord-Bot?

**Comment by BackedUpBooty** [comment]
Awesome thanks, pulled and recreated the container, no further Discord 'Add' issues. 

Yes I'd followed that link instructions for setting up the bot. I created more than one as well to make sure I hadn't clicked a different checkbox by accident, all three of them threw the same embed link error on my system. The latest image though hasn't thrown it (I haven't changed any bot parameters, promise!), so it may have been linked to the 'interaction failed' error. 

EDIT: scratch that, the embed link error is now coming up every 5 minutes or so. It's a weird one, as it doesn't seem to affect functionality (for what I've been using it for at any rate)
